# Generated by Django 2.2.4 on 2019-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20190812_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('PREMIUM', 'PREMIUM'), ('MODERATOR', 'MODERATOR')], default='REGULAR', max_length=20),
        ),
    ]
