# Generated by Django 2.2.3 on 2019-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='tourist_spots_images')),
            ],
        ),
    ]
