# Generated by Django 2.2.3 on 2019-07-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
