# Generated by Django 2.2.4 on 2019-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0002_touristspot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
