# Generated by Django 2.2.3 on 2019-07-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0002_auto_20190727_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
    ]
