# Generated by Django 2.2.3 on 2019-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
        ('tourist_spots_app', '0003_touristspots_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='comments',
            field=models.ManyToManyField(to='comments_app.Comment'),
        ),
    ]
