# Generated by Django 2.2.3 on 2019-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_auto_20190715_1934'),
        ('tourist_spots_app', '0004_touristspots_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='reviews',
            field=models.ManyToManyField(to='reviews_app.Review'),
        ),
    ]
