# Generated by Django 2.2.3 on 2019-07-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0006_auto_20190715_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='attractions_app.Attraction'),
        ),
        migrations.AlterField(
            model_name='touristspots',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments_app.Comment'),
        ),
        migrations.AlterField(
            model_name='touristspots',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews_app.Review'),
        ),
    ]
