# Generated by Django 2.2.3 on 2019-07-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_auto_20190715_1934'),
        ('comments_app', '0002_auto_20190715_1934'),
        ('attractions_app', '0001_initial'),
        ('tourist_spots_app', '0007_auto_20190715_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspots',
            name='attractions',
        ),
        migrations.AddField(
            model_name='touristspots',
            name='attractions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions_app.Attraction'),
        ),
        migrations.RemoveField(
            model_name='touristspots',
            name='comments',
        ),
        migrations.AddField(
            model_name='touristspots',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_app.Comment'),
        ),
        migrations.RemoveField(
            model_name='touristspots',
            name='reviews',
        ),
        migrations.AddField(
            model_name='touristspots',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews_app.Review'),
        ),
    ]
