# Generated by Django 2.2.3 on 2019-07-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses_app', '0001_initial'),
        ('tourist_spots_app', '0009_auto_20190715_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='adress',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses_app.Address'),
            preserve_default=False,
        ),
    ]
