# Generated by Django 2.2.3 on 2019-07-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0010_touristspots_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspots',
            old_name='adress',
            new_name='address',
        ),
    ]
