# Generated by Django 2.2.3 on 2019-07-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
    ]
