# Generated by Django 2.2.3 on 2019-07-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_spots_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.CharField(blank=True, default='', max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=70)),
                ('latitude', models.IntegerField(blank=True, default=0)),
                ('longitude', models.IntegerField(blank=True, default=0)),
                ('tourist_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourist_spots_app.TouristSpot')),
            ],
        ),
    ]
