# Generated by Django 2.2.3 on 2019-07-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots_app', '0003_remove_touristspot_address'),
        ('addresses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tourist_spot',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tourist_spots_app.TouristSpot'),
            preserve_default=False,
        ),
    ]
