# Generated by Django 2.2.3 on 2019-07-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses_app', '0002_auto_20190727_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='tourist_spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourist_spots_app.TouristSpot'),
        ),
    ]
