# Generated by Django 2.2.3 on 2019-07-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attractions_images'),
        ),
    ]
