# Generated by Django 2.2.3 on 2019-07-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_spots_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_spots_app.TouristSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
